query GetIssues($lastCursor: String) {
    search(query: "is:public stars:>2000 good-first-issues:>0 help-wanted-issues:>0", type: REPOSITORY, first: 100, after: $lastCursor) {
        edges {
        node {
            ... on Repository {
            issues(filterBy: {states: OPEN, labels: "good first issue"}, first: 100) {
                edges {
                node {
                    title
                    number
                }
                }
                totalCount
            }
            nameWithOwner
            primaryLanguage {
                name
            }
            }
        }
        cursor
        }
    }
    rateLimit {
        cost
        limit
        remaining
    }
}
